import type { TriviaQuestion } from './types';

export const BIOLOGY_QUESTIONS: readonly TriviaQuestion[] = [
  {
    id: 'bio-01',
    category: 'biology',
    difficulty: 'easy',
    prompt: 'Which organelle produces most of a cell’s ATP?',
    correct: 'Mitochondrion',
    distractors: ['Ribosome', 'Golgi apparatus', 'Nucleus'],
    fact: 'Oxidative phosphorylation runs on the inner mitochondrial membrane.',
  },
  {
    id: 'bio-02',
    category: 'biology',
    difficulty: 'easy',
    prompt: 'Sleep-medicine consensus recommends how much sleep per night for adults?',
    correct: '7 hours or more',
    distractors: ['4–5 hours', '5–6 hours', 'At least 10 hours'],
    fact: 'The AASM and Sleep Research Society consensus sets 7+ hours for adults 18–60.',
  },
  {
    id: 'bio-03',
    category: 'biology',
    difficulty: 'easy',
    prompt: 'Which hormone, released in darkness, helps regulate the sleep–wake cycle?',
    correct: 'Melatonin',
    distractors: ['Cortisol', 'Adrenaline', 'Insulin'],
    fact: 'The pineal gland secretes it; bright evening light suppresses it.',
  },
  {
    id: 'bio-04',
    category: 'biology',
    difficulty: 'medium',
    prompt: 'What does VO₂ max measure?',
    correct: 'Maximum rate of oxygen use during exercise',
    distractors: ['Lung volume at rest', 'Maximum heart rate', 'Blood oxygen saturation at rest'],
    fact: 'It is a standard marker of cardiorespiratory fitness.',
  },
  {
    id: 'bio-05',
    category: 'biology',
    difficulty: 'easy',
    prompt: 'Which neurotransmitter is most associated with reward prediction and motivation?',
    correct: 'Dopamine',
    distractors: ['Serotonin', 'GABA', 'Acetylcholine'],
    fact: 'Dopamine neurons signal the gap between expected and received reward.',
  },
  {
    id: 'bio-06',
    category: 'biology',
    difficulty: 'easy',
    prompt: 'In DNA, adenine pairs with:',
    correct: 'Thymine',
    distractors: ['Guanine', 'Cytosine', 'Uracil'],
    fact: 'In RNA, uracil takes thymine’s place.',
  },
  {
    id: 'bio-07',
    category: 'biology',
    difficulty: 'medium',
    prompt: 'Which brain structure is essential for forming new long-term declarative memories?',
    correct: 'Hippocampus',
    distractors: ['Cerebellum', 'Amygdala', 'Medulla oblongata'],
    fact: 'Patient H.M. lost this ability after surgery removed much of both hippocampi in 1953.',
  },
  {
    id: 'bio-08',
    category: 'biology',
    difficulty: 'easy',
    prompt: 'Which macronutrient provides about 9 kcal per gram?',
    correct: 'Fat',
    distractors: ['Protein', 'Carbohydrate', 'Fibre'],
    fact: 'Protein and carbohydrate each provide about 4 kcal per gram.',
  },
  {
    id: 'bio-09',
    category: 'biology',
    difficulty: 'medium',
    prompt: 'Roughly what share of an adult human’s body mass is water?',
    correct: 'About 60%',
    distractors: ['About 30%', 'About 45%', 'About 80%'],
    fact: 'Typically 50–65%, varying with age, sex and body composition.',
  },
  {
    id: 'bio-10',
    category: 'biology',
    difficulty: 'easy',
    prompt: 'What is the roughly 24-hour internal clock of the body called?',
    correct: 'Circadian rhythm',
    distractors: ['Ultradian rhythm', 'Metabolic cycle', 'Homeostasis'],
    fact: 'The suprachiasmatic nucleus keeps it aligned with daylight.',
  },
];
