import type { TriviaQuestion } from './types';

export const COMPUTER_SCIENCE_QUESTIONS: readonly TriviaQuestion[] = [
  {
    id: 'cs-01',
    category: 'computer_science',
    difficulty: 'easy',
    prompt: 'What is the time complexity of binary search on a sorted array?',
    correct: 'O(log n)',
    distractors: ['O(n)', 'O(1)', 'O(n log n)'],
    fact: 'Each comparison halves the remaining range.',
  },
  {
    id: 'cs-02',
    category: 'computer_science',
    difficulty: 'easy',
    prompt: 'Which data structure is last-in, first-out?',
    correct: 'Stack',
    distractors: ['Queue', 'Heap', 'Hash table'],
    fact: 'Call stacks are why recursion unwinds in reverse order.',
  },
  {
    id: 'cs-03',
    category: 'computer_science',
    difficulty: 'medium',
    prompt: 'What is the worst-case time complexity of quicksort?',
    correct: 'O(n²)',
    distractors: ['O(n log n)', 'O(n)', 'O(log n)'],
    fact: 'Consistently bad pivots degrade it; the average case is O(n log n).',
  },
  {
    id: 'cs-04',
    category: 'computer_science',
    difficulty: 'medium',
    prompt: 'Which problem did Alan Turing prove undecidable in 1936?',
    correct: 'The halting problem',
    distractors: ['The travelling salesman problem', 'Graph colouring', 'P versus NP'],
    fact: 'No program can decide, for every program and input, whether it halts.',
  },
  {
    id: 'cs-05',
    category: 'computer_science',
    difficulty: 'medium',
    prompt: 'To send a message only the recipient can read, you encrypt it with:',
    correct: "The recipient's public key",
    distractors: ["The recipient's private key", 'Your private key', 'Your public key'],
    fact: 'Only the matching private key decrypts it. Signing uses your private key instead.',
  },
  {
    id: 'cs-06',
    category: 'computer_science',
    difficulty: 'easy',
    prompt: 'What is 0xFF in decimal?',
    correct: '255',
    distractors: ['256', '15', '240'],
    fact: '15 × 16 + 15 = 255: the largest value of one byte.',
  },
  {
    id: 'cs-07',
    category: 'computer_science',
    difficulty: 'hard',
    prompt:
      'Which hash-function property makes it infeasible to find any two distinct inputs with the same output?',
    correct: 'Collision resistance',
    distractors: ['Preimage resistance', 'Determinism', 'The avalanche effect'],
    fact: 'Preimage resistance is about inverting a given output, a different guarantee.',
  },
  {
    id: 'cs-08',
    category: 'computer_science',
    difficulty: 'medium',
    prompt: 'Which Git command undoes a commit by adding a new commit, without rewriting history?',
    correct: 'git revert',
    distractors: ['git reset --hard', 'git rebase', 'git stash'],
    fact: 'Revert is safe on shared branches; reset rewrites history.',
  },
  {
    id: 'cs-09',
    category: 'computer_science',
    difficulty: 'easy',
    prompt: 'What does HTTP status 404 mean?',
    correct: 'Not Found',
    distractors: ['Forbidden', 'Internal Server Error', 'Too Many Requests'],
    fact: '403 is Forbidden, 429 Too Many Requests, 500 Internal Server Error.',
  },
];
