import type { TriviaQuestion } from './types';

export const MATHEMATICS_QUESTIONS: readonly TriviaQuestion[] = [
  {
    id: 'math-01',
    category: 'mathematics',
    difficulty: 'easy',
    prompt: 'What is the derivative of x³?',
    correct: '3x²',
    distractors: ['x²', '3x³', 'x⁴/4'],
    fact: 'Power rule: d/dx xⁿ = n·xⁿ⁻¹.',
  },
  {
    id: 'math-02',
    category: 'mathematics',
    difficulty: 'easy',
    prompt: 'What is the sum of the interior angles of a hexagon?',
    correct: '720°',
    distractors: ['540°', '360°', '1080°'],
    fact: 'An n-gon has (n − 2) × 180° of interior angles.',
  },
  {
    id: 'math-03',
    category: 'mathematics',
    difficulty: 'medium',
    prompt: 'Which of these numbers is prime?',
    correct: '97',
    distractors: ['51', '87', '91'],
    fact: '51 = 3·17, 87 = 3·29, 91 = 7·13; 97 has no divisor up to its square root.',
  },
  {
    id: 'math-04',
    category: 'mathematics',
    difficulty: 'medium',
    prompt: 'What is e^(iπ) + 1?',
    correct: '0',
    distractors: ['1', '−1', '2π'],
    fact: "Euler's identity links e, i, π, 1 and 0 in one equation.",
  },
  {
    id: 'math-05',
    category: 'mathematics',
    difficulty: 'easy',
    prompt: 'How many edges does a cube have?',
    correct: '12',
    distractors: ['8', '6', '24'],
    fact: 'A cube has 8 vertices, 12 edges and 6 faces: 8 − 12 + 6 = 2.',
  },
  {
    id: 'math-06',
    category: 'mathematics',
    difficulty: 'medium',
    prompt: 'Rolling two fair six-sided dice, what is the probability the sum is 7?',
    correct: '1/6',
    distractors: ['1/12', '7/36', '1/36'],
    fact: 'Six of the 36 equally likely outcomes sum to 7.',
  },
  {
    id: 'math-07',
    category: 'mathematics',
    difficulty: 'easy',
    prompt: 'What is log₂(64)?',
    correct: '6',
    distractors: ['8', '32', '5'],
    fact: '2⁶ = 64.',
  },
  {
    id: 'math-08',
    category: 'mathematics',
    difficulty: 'medium',
    prompt: 'What is the antiderivative of 1/x?',
    correct: 'ln|x| + C',
    distractors: ['−1/x² + C', 'x⁰ + C', 'eˣ + C'],
    fact: 'The natural logarithm is the integral of 1/t from 1 to x.',
  },
  {
    id: 'math-09',
    category: 'mathematics',
    difficulty: 'easy',
    prompt: 'In how many orders can 5 different people stand in a line?',
    correct: '120',
    distractors: ['25', '60', '3125'],
    fact: '5! = 5 × 4 × 3 × 2 × 1 = 120.',
  },
  {
    id: 'math-10',
    category: 'mathematics',
    difficulty: 'easy',
    prompt: 'What is 1 + 2 + 3 + … + 100?',
    correct: '5050',
    distractors: ['5000', '10100', '4950'],
    fact: 'Pair the ends: 50 pairs of 101.',
  },
];
