import type { TriviaQuestion } from './types';

export const PHYSICS_QUESTIONS: readonly TriviaQuestion[] = [
  {
    id: 'phys-01',
    category: 'physics',
    difficulty: 'easy',
    prompt: 'What is the SI unit of force?',
    correct: 'Newton',
    distractors: ['Joule', 'Watt', 'Pascal'],
    fact: '1 N = 1 kg·m/s².',
  },
  {
    id: 'phys-02',
    category: 'physics',
    difficulty: 'easy',
    prompt: 'The speed of light in a vacuum is closest to:',
    correct: '300,000 km/s',
    distractors: ['30,000 km/s', '3,000,000 km/s', '3,000 km/s'],
    fact: 'Exactly 299,792,458 m/s, by the definition of the metre.',
  },
  {
    id: 'phys-03',
    category: 'physics',
    difficulty: 'medium',
    prompt:
      'Which quantity is conserved in a perfectly elastic collision but not in an inelastic one?',
    correct: 'Kinetic energy',
    distractors: ['Momentum', 'Mass', 'Electric charge'],
    fact: 'Momentum is conserved in both; inelastic collisions turn kinetic energy into heat or deformation.',
  },
  {
    id: 'phys-04',
    category: 'physics',
    difficulty: 'easy',
    prompt: 'Free-fall acceleration at the Earth’s surface is about:',
    correct: '9.8 m/s²',
    distractors: ['1.6 m/s²', '98 m/s²', '3.7 m/s²'],
    fact: 'Standard gravity is defined as 9.80665 m/s².',
  },
  {
    id: 'phys-05',
    category: 'physics',
    difficulty: 'medium',
    prompt: 'If a car doubles its speed, its kinetic energy:',
    correct: 'Quadruples',
    distractors: ['Doubles', 'Stays the same', 'Triples'],
    fact: 'Kinetic energy is ½mv², so it scales with the square of speed.',
  },
  {
    id: 'phys-06',
    category: 'physics',
    difficulty: 'easy',
    prompt: 'Which particle carries no electric charge?',
    correct: 'Neutron',
    distractors: ['Proton', 'Electron', 'Positron'],
    fact: 'Neutrons are neutral; they bind nuclei together with protons.',
  },
  {
    id: 'phys-07',
    category: 'physics',
    difficulty: 'easy',
    prompt: 'Absolute zero is:',
    correct: '−273.15 °C',
    distractors: ['−459.67 °C', '−100 °C', '0 °C'],
    fact: '0 K = −273.15 °C (= −459.67 °F).',
  },
  {
    id: 'phys-08',
    category: 'physics',
    difficulty: 'medium',
    prompt: 'Which law says the entropy of an isolated system never decreases?',
    correct: 'The second law of thermodynamics',
    distractors: [
      'The first law of thermodynamics',
      "Newton's third law",
      'The zeroth law of thermodynamics',
    ],
    fact: 'The first law is energy conservation; the second gives time its direction.',
  },
  {
    id: 'phys-09',
    category: 'physics',
    difficulty: 'medium',
    prompt: 'The Heisenberg uncertainty principle limits how precisely we can know both:',
    correct: 'Position and momentum',
    distractors: ['Mass and charge', 'Voltage and current', 'Temperature and pressure'],
    fact: 'Δx·Δp ≥ ħ/2.',
  },
];
