import type { TriviaQuestion } from './types';

export const SPACE_QUESTIONS: readonly TriviaQuestion[] = [
  {
    id: 'space-01',
    category: 'space',
    difficulty: 'easy',
    prompt: 'What is the largest planet in the Solar System?',
    correct: 'Jupiter',
    distractors: ['Saturn', 'Neptune', 'Earth'],
    fact: 'Jupiter has more than twice the mass of all the other planets combined.',
  },
  {
    id: 'space-02',
    category: 'space',
    difficulty: 'easy',
    prompt: 'Sunlight takes about how long to reach Earth?',
    correct: '8 minutes',
    distractors: ['8 seconds', '8 hours', '1 hour'],
    fact: 'About 499 seconds across one astronomical unit.',
  },
  {
    id: 'space-03',
    category: 'space',
    difficulty: 'medium',
    prompt: 'Which star is closest to the Sun?',
    correct: 'Proxima Centauri',
    distractors: ['Sirius', "Barnard's Star", 'Vega'],
    fact: 'About 4.24 light-years away, in the Alpha Centauri system.',
  },
  {
    id: 'space-04',
    category: 'space',
    difficulty: 'medium',
    prompt: 'Escape velocity from the Earth’s surface is about:',
    correct: '11.2 km/s',
    distractors: ['7.9 km/s', '16.7 km/s', '29.8 km/s'],
    fact: '7.9 km/s is low orbit; 29.8 km/s is Earth’s own speed around the Sun.',
  },
  {
    id: 'space-05',
    category: 'space',
    difficulty: 'medium',
    prompt: 'Which spacecraft was the first to enter interstellar space?',
    correct: 'Voyager 1',
    distractors: ['Pioneer 10', 'New Horizons', 'Voyager 2'],
    fact: 'It crossed the heliopause in August 2012; Voyager 2 followed in 2018.',
  },
  {
    id: 'space-06',
    category: 'space',
    difficulty: 'medium',
    prompt: 'What type of galaxy is the Milky Way?',
    correct: 'Barred spiral',
    distractors: ['Elliptical', 'Irregular', 'Lenticular'],
    fact: 'A central bar of stars feeds its spiral arms.',
  },
  {
    id: 'space-07',
    category: 'space',
    difficulty: 'easy',
    prompt: 'What is the boundary around a black hole beyond which nothing can escape?',
    correct: 'The event horizon',
    distractors: ['The photon sphere', 'The accretion disk', 'The singularity'],
    fact: 'For a non-rotating black hole its radius is the Schwarzschild radius.',
  },
  {
    id: 'space-08',
    category: 'space',
    difficulty: 'easy',
    prompt: 'About how old is the universe?',
    correct: '13.8 billion years',
    distractors: ['4.6 billion years', '100 billion years', '6,000 years'],
    fact: '4.6 billion years is the age of the Solar System.',
  },
  {
    id: 'space-09',
    category: 'space',
    difficulty: 'easy',
    prompt: 'What was the first artificial satellite to orbit the Earth?',
    correct: 'Sputnik 1',
    distractors: ['Explorer 1', 'Vostok 1', 'Telstar 1'],
    fact: 'Launched by the Soviet Union on 4 October 1957.',
  },
  {
    id: 'space-10',
    category: 'space',
    difficulty: 'medium',
    prompt: 'One astronomical unit (AU) is approximately:',
    correct: '150 million km',
    distractors: ['15 million km', '1.5 billion km', '384,000 km'],
    fact: 'The mean Earth–Sun distance; 384,000 km is the Earth–Moon distance.',
  },
];
