import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';
import {
  ApplicationCommandOptionType,
  ApplicationCommandType,
  type APIApplicationCommandOption,
} from 'discord.js';
import { REQUIRED_PERMISSIONS } from '../discord/permissions';
import { CATEGORY_ORDER } from '../features/core/help';
import type { BotFeature } from '../features/types';
import type { CommandDefinition } from '../interactions/types';

/** The repository root, where COMMANDS.md lives. */
export const REPO_ROOT = fileURLToPath(new URL('../../../../', import.meta.url));
export const COMMANDS_DOC_PATH = `${REPO_ROOT}COMMANDS.md`;
/** Per-feature pages live at docs/commands/<feature>.md. */
const FEATURE_DOCS_DIR = 'docs/commands';
const UNLISTED_LABEL = 'Not listed in /help';

interface FeatureCommand {
  feature: string;
  command: CommandDefinition;
}

function cell(text: string): string {
  return text.replaceAll('|', '\\|').replaceAll('\n', ' ');
}

/** `a` · `b create` · … for every subcommand, including those inside groups. */
function subcommandNames(options: readonly APIApplicationCommandOption[] | undefined): string[] {
  const names: string[] = [];
  for (const option of options ?? []) {
    if (option.type === ApplicationCommandOptionType.Subcommand) names.push(option.name);
    if (option.type === ApplicationCommandOptionType.SubcommandGroup) {
      for (const sub of option.options ?? []) names.push(`${option.name} ${sub.name}`);
    }
  }
  return names;
}

function slashOptions(command: CommandDefinition): readonly APIApplicationCommandOption[] {
  const data = command.data;
  if (data.type !== undefined && data.type !== ApplicationCommandType.ChatInput) return [];
  return 'options' in data && data.options ? data.options : [];
}

function description(command: CommandDefinition): string {
  if (command.help) return command.help.summary;
  return 'description' in command.data && command.data.description ? command.data.description : '—';
}

function detailsLink(feature: string, docExists: (path: string) => boolean): string {
  const path = `${FEATURE_DOCS_DIR}/${feature}.md`;
  return docExists(path) ? `[${feature}](${path})` : '—';
}

function slashTable(entries: readonly FeatureCommand[], docExists: (p: string) => boolean) {
  const lines = [
    '| Command | Subcommands | What it does | Listed for | Details |',
    '| ------- | ----------- | ------------ | ---------- | ------- |',
  ];
  for (const { feature, command } of entries) {
    const subs = subcommandNames(slashOptions(command))
      .map((name) => `\`${name}\``)
      .join(' · ');
    lines.push(
      `| \`/${command.data.name}\` | ${subs || '—'} | ${cell(description(command))} | ${
        command.requires ? `\`${command.requires}\`` : 'everyone'
      } | ${detailsLink(feature, docExists)} |`,
    );
  }
  return lines;
}

/**
 * COMMANDS.md, rendered from the live command definitions: what `/help`
 * lists, plus every context menu and the bot's permission set. Pure, so a
 * test can compare the committed file with what the code would write.
 */
export function renderCommandsDoc(
  features: readonly BotFeature[],
  docExists: (repoRelativePath: string) => boolean,
): string {
  const all: FeatureCommand[] = features.flatMap((feature) =>
    (feature.commands ?? []).map((command) => ({ feature: feature.name, command })),
  );
  const slash = all.filter((entry) => entry.command.kind === 'slash');
  const menus = all.filter((entry) => entry.command.kind !== 'slash');
  const byName = (a: FeatureCommand, b: FeatureCommand) =>
    a.command.data.name.localeCompare(b.command.data.name);

  const out: string[] = [
    '# Commands',
    '',
    '<!-- Generated by `pnpm --filter @jave/bot commands:doc` from the command definitions. Do not edit by hand; a test fails when this file is out of date. -->',
    '',
    `JAVE registers ${slash.length} slash commands and ${menus.length} context menus. This page is the`,
    'index; each feature page describes the full flows (buttons, selects, forms), who may do',
    'what, and the Discord permissions involved.',
    '',
    '- **Listed for**: the capability `/help` requires before it lists the command. It is a',
    '  convenience, not the security boundary: every subcommand, button and form calls',
    '  `@jave/core` as the person who used it, and core checks their capabilities.',
    '- Replies are ephemeral (only you see them) unless a feature page says otherwise.',
    '- Custom ids on buttons and forms route an interaction; they never authorize it.',
    '',
    '## Slash commands',
  ];

  const categories = [
    ...CATEGORY_ORDER.map(({ key, label }) => ({
      label,
      entries: slash.filter((entry) => entry.command.help?.category === key),
    })),
    { label: UNLISTED_LABEL, entries: slash.filter((entry) => !entry.command.help) },
  ];
  for (const { label, entries } of categories) {
    if (entries.length === 0) continue;
    out.push('', `### ${label}`, '', ...slashTable([...entries].sort(byName), docExists));
  }

  out.push(
    '',
    '## Context menus',
    '',
    'Right-click a member or a message → **Apps**.',
    '',
    '| Name | On | Listed for | Details |',
    '| ---- | -- | ---------- | ------- |',
  );
  for (const { feature, command } of [...menus].sort(byName)) {
    const target = command.kind === 'user_context' ? 'member' : 'message';
    out.push(
      `| ${cell(command.data.name)} | ${target} | ${
        command.requires ? `\`${command.requires}\`` : 'everyone'
      } | ${detailsLink(feature, docExists)} |`,
    );
  }

  out.push(
    '',
    '## Bot permissions',
    '',
    'The bot asks for exactly these server permissions, never Administrator',
    '(`REQUIRED_PERMISSIONS` in `apps/bot/src/discord/permissions.ts`). `/jave setup` checks',
    'them, channel by channel, in the live server.',
    '',
    '| Permission | Why |',
    '| ---------- | --- |',
    ...Object.entries(REQUIRED_PERMISSIONS).map(([name, why]) => `| ${name} | ${cell(why)} |`),
    '',
  );
  return out.join('\n');
}

/** Resolve repo-relative doc paths against the checkout. */
export function docExistsInRepo(repoRelativePath: string): boolean {
  return existsSync(`${REPO_ROOT}${repoRelativePath}`);
}

/** The document as committed: rendered, then formatted with the repository's Prettier config. */
export async function formatCommandsDoc(
  features: readonly BotFeature[],
  docExists: (repoRelativePath: string) => boolean,
): Promise<string> {
  const options = (await resolveConfig(COMMANDS_DOC_PATH)) ?? {};
  return format(renderCommandsDoc(features, docExists), { ...options, parser: 'markdown' });
}
